/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Edward VanDerJagt
 */
public class GUISimulator extends javax.swing.JFrame
{
private Simulation Gsim;
   private Customer Gcust;
   private int Gtime = 0;
   /**
    * Creates new form NewJFrame
    */
   public GUISimulator()
   {
      initComponents();
      Gcust = new Customer(0);
      Gsim = new Simulation();
   }

   /**
    * This method is called from within the constructor to initialize the
    * form. WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      Header = new javax.swing.JLabel();
      ClockLabel = new javax.swing.JLabel();
      TimeNow = new javax.swing.JLabel();
      ClockBtn = new javax.swing.JButton();
      ArrBtn = new javax.swing.JButton();
      LveBtn = new javax.swing.JButton();
      StatBtn = new javax.swing.JButton();
      WaitLabel = new javax.swing.JLabel();
      WaitNum = new javax.swing.JLabel();
      ServedNow = new javax.swing.JLabel();
      ServeLabel = new javax.swing.JLabel();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTextArea1 = new javax.swing.JTextArea();
      Cheat = new javax.swing.JButton();
      jScrollPane2 = new javax.swing.JScrollPane();
      debuggy = new javax.swing.JTextArea();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      Header.setText("Platteville Burger Waiting Line Simulator");

      ClockLabel.setText("Clock");

      TimeNow.setText("Time Now 0");
      TimeNow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

      ClockBtn.setText("Clock +1");
      ClockBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            ClockBtnActionPerformed(evt);
         }
      });

      ArrBtn.setText("Arrive");
      ArrBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            ArrBtnActionPerformed(evt);
         }
      });

      LveBtn.setText("Leave");
      LveBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            LveBtnActionPerformed(evt);
         }
      });

      StatBtn.setText("Statistics");
      StatBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            StatBtnActionPerformed(evt);
         }
      });

      WaitLabel.setText("Number of Customers Waiting");

      WaitNum.setText("0 Customers Waiting");
      WaitNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

      ServedNow.setText("Being Served Now");
      ServedNow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

      ServeLabel.setText("Customer Being Served");

      jTextArea1.setColumns(20);
      jTextArea1.setRows(5);
      jScrollPane1.setViewportView(jTextArea1);

      Cheat.setText("Display");

      debuggy.setColumns(20);
      debuggy.setRows(5);
      jScrollPane2.setViewportView(debuggy);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(ClockBtn)
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ArrBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LveBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(StatBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(Header)
                           .addGroup(layout.createSequentialGroup()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addComponent(ServeLabel)
                                 .addComponent(ClockLabel))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addComponent(TimeNow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                 .addComponent(ServedNow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                     .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(Cheat)
                           .addComponent(WaitLabel))
                        .addGap(18, 18, 18)
                        .addComponent(WaitNum, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                  .addGap(0, 2, Short.MAX_VALUE))
               .addComponent(jScrollPane2))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(Header)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(ClockLabel)
               .addComponent(TimeNow)
               .addComponent(ClockBtn))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(ArrBtn)
               .addComponent(ServeLabel)
               .addComponent(ServedNow))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(LveBtn)
               .addComponent(WaitLabel)
               .addComponent(WaitNum))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(StatBtn)
               .addComponent(Cheat))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(16, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void ClockBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ClockBtnActionPerformed
   {//GEN-HEADEREND:event_ClockBtnActionPerformed
      // Call AdvanceTime
      Gsim.advanceTime(1);
      //Gsim.simNQ();
      ++Gtime;
      //TimeNow.setText(" ");
      TimeNow.setText("The time is: " + Gtime);
      debuggy.setText("get time = " + Gsim.simDebuggy());
// TODO add your handling code here:
   }//GEN-LAST:event_ClockBtnActionPerformed

   private void ArrBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ArrBtnActionPerformed
   {//GEN-HEADEREND:event_ArrBtnActionPerformed
      Gsim.simNQ(); // TODO add your handling code here:
      debuggy.setText("Cust Arrived /n" + Gsim.simDebuggy());
   }//GEN-LAST:event_ArrBtnActionPerformed

   private void LveBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_LveBtnActionPerformed
   {//GEN-HEADEREND:event_LveBtnActionPerformed
   Customer y = Gsim.gDQ();      // TODO add your handling code here:

   }//GEN-LAST:event_LveBtnActionPerformed

   private void StatBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_StatBtnActionPerformed
   {//GEN-HEADEREND:event_StatBtnActionPerformed
      debuggy.setText(debuggy.getText() + "\n" + Gsim.stats());

   }//GEN-LAST:event_StatBtnActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try
      {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
         {
            if ("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      }
      catch (ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(GUISimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(GUISimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(GUISimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(GUISimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
        //</editor-fold>
        //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new GUISimulator().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton ArrBtn;
   private javax.swing.JButton Cheat;
   private javax.swing.JButton ClockBtn;
   private javax.swing.JLabel ClockLabel;
   private javax.swing.JLabel Header;
   private javax.swing.JButton LveBtn;
   private javax.swing.JLabel ServeLabel;
   private javax.swing.JLabel ServedNow;
   private javax.swing.JButton StatBtn;
   private javax.swing.JLabel TimeNow;
   private javax.swing.JLabel WaitLabel;
   private javax.swing.JLabel WaitNum;
   private javax.swing.JTextArea debuggy;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JTextArea jTextArea1;
   // End of variables declaration//GEN-END:variables
}
